In [1]:
base_dir = './'
data_dir = './data/'

In [2]:
import os
import sys

sys.path.insert(0, os.getcwd() + '\\src')

In [3]:
from preprocess import *

In [4]:
data = load_data(data_dir + 'USD2FX_BIS_daily_avg.csv', 
                 start_date = '2002-01-01', 
                 end_date = '2022-10-31'
                )
data

,AED,ALL,ARS,EUR,AUD,BAM,EUR.1,BGN,BHD,BND,...,TRY,TTD,TWD,UAH,USD,UYU,VEF,EUR.19,XDR,ZAR
Date,,,,,,,,,,,,,,,,,,,,,
2002-01-01,NaN,136.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.2985,1.0,NaN,NaN,NaN,0.7957,NaN
2002-01-02,3.6725,136.800,0.999657,1.106439,1.947665,NaN,1.106439,2.159659,0.376,1.8494,...,1.450542,6.2437,35.074131,NaN,1.0,14.7795,0.75950,1.106439,0.7957,12.283027
2002-01-03,3.6725,136.375,0.999104,1.106684,1.938911,NaN,1.106684,2.161355,0.376,1.8485,...,1.432050,6.2591,35.015494,5.2985,1.0,14.7845,0.75976,1.106684,0.7914,12.301018
2002-01-04,3.6725,137.150,0.999095,1.116819,1.929864,NaN,1.116819,2.182153,0.376,1.8467,...,1.419477,6.2385,35.003350,5.2985,1.0,14.7895,0.76000,1.116819,0.7933,12.119946
2002-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.3030,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-27,3.6725,117.830,155.698300,0.996314,1.555246,1.951342,0.996314,1.948590,NaN,1.4061,...,18.612135,6.7403,31.990000,36.5686,1.0,40.7650,NaN,0.996314,0.7750,18.085185
2022-10-28,3.6725,118.880,156.016700,1.004924,1.558738,1.948620,1.004924,1.965431,NaN,1.4057,...,18.613104,6.7369,32.130000,36.5686,1.0,40.5690,NaN,1.004924,0.7780,18.141895
2022-10-29,3.6725,NaN,NaN,NaN,NaN,1.965461,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-30,3.6725,NaN,NaN,NaN,NaN,1.965461,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-31,3.6725,118.760,156.895000,1.008675,1.566371,1.965461,1.008675,1.972766,NaN,1.4112,...,18.616300,6.7301,32.260000,36.5686,1.0,40.6080,NaN,1.008675,0.7792,18.331249

In [5]:
n_timestamps = 28
lag = 1

save_dir = data_dir+f'/n_timestamps_{n_timestamps}__lag_{lag}'

In [6]:
data = cleanse_data(data, save_dir=save_dir)
data

,AUD,BGN,BRL,CAD,CHF,CNY,COP,CZK,DKK,DZD,...,PHP,PLN,RON,RUB,SEK,SGD,THB,TRY,TWD,ZAR
Date,,,,,,,,,,,,,,,,,,,,,
2002-01-02,0.194767,0.215966,0.230825,0.159726,0.164118,0.827705,0.229118,0.350819,0.823058,0.762215,...,0.517493,0.393981,0.317404,0.305237,1.027052,0.185185,0.442091,0.145054,0.350741,1.228303
2002-01-03,0.193891,0.216135,0.229405,0.159606,0.164409,0.827700,0.228942,0.352512,0.823152,0.759540,...,0.515837,0.394976,0.319201,0.306278,1.021879,0.184916,0.440454,0.143205,0.350155,1.230102
2002-01-04,0.192986,0.218215,0.230802,0.159761,0.165166,0.827697,0.228991,0.356623,0.830969,0.763530,...,0.516652,0.393846,0.320717,0.305452,1.031416,0.184465,0.439298,0.141948,0.350033,1.211995
2002-01-07,0.192925,0.219427,0.235295,0.159596,0.165289,0.827703,0.229559,0.359573,0.835362,0.767929,...,0.514733,0.391600,0.323414,0.305568,1.034363,0.184627,0.438576,0.140146,0.349332,1.189253
2002-01-08,0.192053,0.219329,0.233853,0.160141,0.165035,0.827702,0.229559,0.362072,0.835009,0.767689,...,0.516938,0.393647,0.320889,0.306116,1.036626,0.184970,0.440998,0.139297,0.350601,1.162499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-25,0.158189,0.198337,0.529906,0.137278,0.100274,0.730879,0.496894,0.248170,0.754355,1.401180,...,0.588054,0.484434,0.497272,0.611629,1.112747,0.142481,0.382902,1.860947,0.323400,1.847794
2022-10-26,0.154305,0.195131,0.528225,0.135369,0.098942,0.717829,0.494814,0.244787,0.742103,1.400837,...,0.583588,0.474389,0.486940,0.613326,1.092787,0.140716,0.377751,1.860331,0.321000,1.797985
2022-10-27,0.155525,0.194859,0.536903,0.136216,0.099123,0.722846,0.489529,0.244396,0.741128,1.401787,...,0.582256,0.474096,0.487128,0.614277,1.091790,0.141018,0.378350,1.861214,0.319900,1.808518
2022-10-28,0.155874,0.196543,0.535323,0.136087,0.099688,0.725143,0.482192,0.245855,0.747895,1.404132,...,0.580233,0.475078,0.494312,0.613589,1.099417,0.141242,0.379098,1.861310,0.321300,1.814190
2022-10-31,0.156637,0.197277,0.531511,0.136706,0.100111,0.730079,0.481942,0.247004,0.750898,1.403259,...,0.583014,0.474934,0.495693,0.614535,1.099556,0.141598,0.380754,1.861630,0.322600,1.833125

In [7]:
extracted = extract_data(data, n_timestamps=5, lag=1, 
                         save_dir=save_dir
                        )
print('Data :', extracted['data'].shape)
print('Dates :', extracted['dates'].shape)
print('Positional Encoding :', extracted['pos_enc'].shape)

Data : torch.Size([5332, 5, 34])
Dates : (5332,)
Positional Encoding : torch.Size([5332, 5, 2])

In [8]:
data_split = split_data(extracted, save_dir=save_dir)
print('Train :', data_split['train']['data'].shape[0])
print('Valid :', data_split['valid']['data'].shape[0])
print('Test  :', data_split['test']['data'].shape[0])

Train : 3412
Valid : 853
Test  : 1067